print()
sal = float(input("Digite o seu salário: "))
print()
print("Você possui duas contas atrasadas!!")
print()
c1 = float(input("Digite o valor da primeira conta: "))
c2 = float(input("Digiteo o valor da segunda conta: "))
c1j = c1 + (c1*2/100)
c2j = c2 + (c2*2/100)
resto = sal - (c1j + c2j)
print()
print(f"Com um juros de 2% para cada conta a primeira agora custa R${c1j :.2f} e a segunda R${c2j :.2f}!")
print(f"Irão restar R${resto :.2f} do seu salário!")
print()